-- ====================================================================
-- 1. DATABASE TABLES SETUP
-- ====================================================================

create extension if not exists pgcrypto;

create table if not exists public.maze_teams (
  id uuid primary key default gen_random_uuid(),
  team_number integer generated by default as identity,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.maze_settings (
  id text primary key default 'default',
  runs_per_team integer not null default 3 check (runs_per_team between 1 and 10),
  ranking_mode text not null default 'best' check (ranking_mode in ('best','average','total')),
  active_team_id uuid references public.maze_teams(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.maze_settings (id, runs_per_team, ranking_mode)
values ('default', 3, 'best')
on conflict (id) do nothing;

create table if not exists public.maze_runs (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.maze_teams(id) on delete cascade,
  time_ms integer not null check (time_ms > 0),
  source text not null default 'esp32',
  started_at timestamptz,
  finished_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.maze_events (
  id bigserial primary key,
  team_id uuid references public.maze_teams(id) on delete set null,
  team_name text,
  status text not null check (status in ('READY','STARTED','FINISHED','ERROR')),
  time_ms integer,
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.maze_admins (
  user_id uuid primary key,
  created_at timestamptz not null default now()
);

-- ====================================================================
-- 2. ROW LEVEL SECURITY (RLS) ACTIVATION
-- ====================================================================

alter table public.maze_teams enable row level security;
alter table public.maze_settings enable row level security;
alter table public.maze_runs enable row level security;
alter table public.maze_events enable row level security;
alter table public.maze_admins enable row level security;

alter table public.maze_teams force row level security;
alter table public.maze_settings force row level security;
alter table public.maze_runs force row level security;
alter table public.maze_events force row level security;
alter table public.maze_admins force row level security;

-- ====================================================================
-- 3. HELPER FUNCTION (SECURITY DEFINER TO BYPASS RLS LOOPS)
-- ====================================================================

create or replace function public.is_maze_admin()
returns boolean
language sql
stable
security definer -- تخطي قفل الـ RLS اللانهائي أثناء التحقق
as $$
  select exists (
    select 1
    from public.maze_admins
    where user_id = auth.uid()
  );
$$;

-- ====================================================================
-- 4. REVISED RLS POLICIES
-- ====================================================================

-- Maze Admins Table Policies
drop policy if exists "maze_admins_select_self" on public.maze_admins;
create policy "maze_admins_select_authenticated" on public.maze_admins 
  for select to authenticated using (true);

-- Maze Teams Table Policies (Public Read for ESP32/Leaderboard, Admin Write)
drop policy if exists "maze_teams_select" on public.maze_teams;
drop policy if exists "maze_teams_insert" on public.maze_teams;
drop policy if exists "maze_teams_update" on public.maze_teams;
drop policy if exists "maze_teams_delete" on public.maze_teams;

create policy "maze_teams_select" on public.maze_teams for select to anon, authenticated using (true);
create policy "maze_teams_insert" on public.maze_teams for insert to authenticated with check (public.is_maze_admin());
create policy "maze_teams_update" on public.maze_teams for update to authenticated using (public.is_maze_admin()) with check (public.is_maze_admin());
create policy "maze_teams_delete" on public.maze_teams for delete to authenticated using (public.is_maze_admin());

-- Maze Settings Table Policies (Public Read, Admin Write)
drop policy if exists "maze_settings_select" on public.maze_settings;
drop policy if exists "maze_settings_update" on public.maze_settings;
drop policy if exists "maze_settings_insert" on public.maze_settings;
drop policy if exists "maze_settings_delete" on public.maze_settings;

create policy "maze_settings_select" on public.maze_settings for select to anon, authenticated using (true);
create policy "maze_settings_update" on public.maze_settings for update to authenticated using (public.is_maze_admin()) with check (public.is_maze_admin());
create policy "maze_settings_insert" on public.maze_settings for insert to authenticated with check (public.is_maze_admin());
create policy "maze_settings_delete" on public.maze_settings for delete to authenticated using (public.is_maze_admin());

-- Maze Runs Table Policies (Public Read, Admin & ESP32 Write)
drop policy if exists "maze_runs_select" on public.maze_runs;
drop policy if exists "maze_runs_insert" on public.maze_runs;
drop policy if exists "maze_runs_update" on public.maze_runs;
drop policy if exists "maze_runs_delete" on public.maze_runs;

create policy "maze_runs_select" on public.maze_runs for select to anon, authenticated using (true);
create policy "maze_runs_insert" on public.maze_runs for insert to anon, authenticated with check (true);
create policy "maze_runs_update" on public.maze_runs for update to authenticated using (public.is_maze_admin()) with check (public.is_maze_admin());
create policy "maze_runs_delete" on public.maze_runs for delete to authenticated using (public.is_maze_admin());

-- Maze Events Table Policies (Public Read, Admin Write)
drop policy if exists "maze_events_select" on public.maze_events;
drop policy if exists "maze_events_insert" on public.maze_events;
drop policy if exists "maze_events_update" on public.maze_events;
drop policy if exists "maze_events_delete" on public.maze_events;

create policy "maze_events_select" on public.maze_events for select to anon, authenticated using (true);
create policy "maze_events_insert" on public.maze_events for insert to anon, authenticated with check (true);
create policy "maze_events_update" on public.maze_events for update to authenticated using (public.is_maze_admin()) with check (public.is_maze_admin());
create policy "maze_events_delete" on public.maze_events for delete to authenticated using (public.is_maze_admin());